; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
lib_deps =
  esp32-camera

;ESP32-CAM AI-Thinker Module Clone - ESP32-CAM Dev Module 4MB Flash - 4MB PSRAM
[env:esp32cam]
; board = esp32cam
board = esp32cam_no_reset_before
build_flags =
  ${env.build_flags}
  ; -DDEBUG
  ; -g
  ; -w             ;supress all warnings
  -DCORE_DEBUG_LEVEL=5
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DESP32BOARD=1
  -DESP32CAMAITHINKER=1
upload_speed = 921600
; upload_speed = 57600
; upload_port = COM18
monitor_speed = 115200
; monitor_port = COM18
lib_deps =
	${env.lib_deps}

;Freenove ESP32-Wrover CAM Board Clone - ESP32-CAM Dev Module 4MB Flash - 4MB PSRAM
[env:freenove_esp32_wroom_no_reset_before]
board = freenove_esp32_wroom_no_reset_before
build_flags =
  ${env.build_flags}
  ; -DDEBUG 
  ; -g
  ; -w             ;supress all warnings
  -DCORE_DEBUG_LEVEL=5
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DESP32BOARD=1
  -DESP32CAMFREENOVE=1
upload_speed = 921600
; upload_port = COM7
upload_protocol = esptool
monitor_speed = 115200
; monitor_port = COM7
lib_deps =
	${env.lib_deps}

;Freenove ESP32-S3-WROOM CAM Board Clone - ESP32-S3-CAM Dev Module 16MB Flash - 8MB PSRAM
[env:freenove_esp32_s3_wroom]
board = freenove_esp32_s3_wroom
build_flags =
  ${env.build_flags}
  ; -DDEBUG
  ; -g
  ; -w             ;supress all warnings
  -DCORE_DEBUG_LEVEL=5
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DESP32CAMFREENOVE_S3=1
upload_speed = 921600
; upload_speed = 115200
; upload_port = COM18
monitor_speed = 115200
; monitor_port = COM18
lib_deps =
	${env.lib_deps}

;Chinese Seller ESP32-S3-WROOM CAM Board Clone - ESP32-S3-CAM Dev Module 16MB Flash - 8MB PSRAM
[env:chinese_seller_esp32_s3_wroom]
board = freenove_esp32_s3_wroom
build_flags =
  ${env.build_flags}
  ; -DDEBUG
  ; -g
  ; -w             ;supress all warnings
  -DCORE_DEBUG_LEVEL=5
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DESP32CAMCHINESESELLER=1
upload_speed = 921600
; upload_speed = 115200
; upload_port = COM18
monitor_speed = 115200
; monitor_port = COM18
lib_deps =
	${env.lib_deps}
